title: "MATH 60630A - Machine Learning II : Deep Learning"
description: HEC Montr√©al
google_analytics:
theme: jekyll-theme-cayman


url: "https://deepgraphlearning.github.io"
baseurl: "/MATH60630A_2024A"
#baseurl: "/"